# プロジェクト全体の共通設定
# 各Workerのwrangler.tomlはこの設定を継承します

# Cloudflareアカウント設定
account_id = "2e20678de4b537ee345e20a75acaeb16"

# 共通の互換性日付
compatibility_date = "2024-01-01"

# D1データベース設定（全Workerで共通）
[[d1_databases]]
binding = "DB"
database_name = "childcare-dashboard"
database_id = "296de5ad-9a75-48b8-aa3e-fff0ac25edff"