name = "childcare-metrics-exporter"
main = "src/index.ts"
compatibility_date = "2024-01-01"
account_id = "2e20678de4b537ee345e20a75acaeb16"

# D1データベース設定
[[d1_databases]]
binding = "DB"
database_name = "childcare-dashboard"
database_id = "296de5ad-9a75-48b8-aa3e-fff0ac25edff"

# 環境変数
[vars]

# 本番環境の秘密情報は wrangler secret で設定（オプション）
# wrangler secret put API_KEY
